substitutions:
  _APP: github.com/project-hermes/hermes-app

steps:

- name: "gcr.io/cloud-builders/go"
  args:
  - get

  - "firebase.google.com/go"
  - "firebase.google.com/go/auth"

  - "github.com/gin-gonic/gin"

  - "google.golang.org/api/iterator"
  - "google.golang.org/api/option"

  - "google.golang.org/appengine"
  - "google.golang.org/appengine/datastore"
  - "google.golang.org/appengine/log"

  - "gopkg.in/check.v1"

  env:
  - "GOPATH=go"

- name: "gcr.io/cloud-builders/git"
  args:
    - clone
    - "https://${_APP}"

- name: "gcr.io/cloud-builders/go"
  args:
    - test
    - "./..."
  env:
    - "GOPATH=/workspace/hermes-app/server:/workspace/go"
  dir: "hermes-app/server"

timeout: "600s"
